version: '3.7'

services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Ehrlich24h
    networks:
      - postgres-network
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres_db
    ports:
    - "15432:80"
    volumes:
    - ./data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin      
    networks:
    - postgres-network
 
networks:
  postgres-network:
    driver: bridge