### 26.May.2022 09:26
### https://www.youtube.com/watch?v=esYVUkFhwik
### https://www.youtube.com/watch?v=lV6vty0Hf_E&list=PLsjmv9aDmNDBwFUXZbdfc4Xauvd-gDsLV&index=7
### https://progressivecoder.com/how-to-send-emails-using-nestjs-sendgrid-api/
### https://docs.nestjs.com/techniques/events#dispatching-events


### Login Valid user auth/login call;
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "baliwme2004@gmail.com",
  "password": "Pass@word1"
}


### Valid auth/register call;
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "baliwme2004@gmail.com",
  "password": "Pass@word1",
  "role": "ADMIN"
}

### Invalid auth/register call;
POST http://localhost:8080/auth/register
Content-Type: application/json


### 
GET http://localhost:8080/images/?limit=h
Content-Type: application/json


### END-OF_DAY##
### 25.May.2022 10:22
### Pipe: https://www.youtube.com/watch?v=DAjF0jkn6Nc AND i6Rt-DpbG_A
### https://www.youtube.com/watch?v=uAKzFhE3rxU
### https://mediajams.dev/post/Signed-Image-Uploading-to-Cloudinary-with-Angular-and-NestJS


###
curl https://api.cloudinary.com/v1_1/demo/image/upload -X POST --data 
'file=https://upload.wikimedia.org/wikipedia/commons/a/ae/Olympic_flag.jpg&public_id=olympic_flag&timestamp=12345678&api_key=98765432&signature=a123456f987664af'

### 11:18 Get nth number of Pexels images at random page:
GET http://localhost:3000/images/?limit=4
Content-Type: application/json


### Pexel API Call with page & per_page: 11:14
GET https://api.pexels.com/v1/search?query=people&page=2&per_page=3
Authorization: Bearer 563492ad6f9170000100000143b1404b9f7e475d8c8831687a2e36a9


### 10:22 Get nth number of Pexels images:
GET http://localhost:3000/images/?limit=5
Content-Type: application/json




### END-OF-DAY ###
### 11:17 Get nth number of Pexels images:
GET http://localhost:3000/images/?limit=7
Content-Type: application/json


### Pexel API Call: 08:11
GET https://api.pexels.com/v1/search?query=people
Authorization: Bearer 563492ad6f9170000100000143b1404b9f7e475d8c8831687a2e36a9


### With value with in the allowed range
GET http://localhost:3000/images/?limit=7
Content-Type: application/json

### With more than 10, 'limit=33', shuould return 10
GET http://localhost:3000/images/?limit=33
Content-Type: application/json

### With invalid 'limit=invalid'
GET http://localhost:3000/images/?limit=invalid
Content-Type: application/json

### 24.May.2022 07:47
### With no limit defined, should return 5 as default
GET http://localhost:3000/images
Content-Type: application/json