### 30.May.2022 10:37
### https://www.youtube.com/watch?v=fqefAY9lXBc
### https://stackoverflow.com/questions/71159026/jest-has-detected-open-handle-for-firstvaluefrom-in-nestjs


### ADMIN DELETE images/9 with Auth:jwt
DELETE http://localhost:8080/images/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY2Fpc2JhY2tAb3V0bG9vay5jb20iLCJpYXQiOjE2NTM4OTcxNTcsImV4cCI6MTY1Mzg5ODA1N30.-Bw0A1Otyi1zSsu4da8zflEPGSKZrKI6sLMRC_96Qag
### USER : Call images/?limit=2 with Auth:jwt image_id(8&9)
GET http://localhost:8080/images/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYmFsaXdtZTIwMTRAZ21haWwuY29tIiwiaWF0IjoxNjUzODk2NjE3LCJleHAiOjE2NTM4OTc1MTd9.I_g2woPxEz6ru-FNXMkuVPc42o53NQBYi7NyS9d_riE


### USER : Call images/?limit=2 with Auth:jwt image_id(8&9)
GET http://localhost:8080/images/?limit=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYmFsaXdtZTIwMTRAZ21haWwuY29tIiwiaWF0IjoxNjUzODk2NjE3LCJleHAiOjE2NTM4OTc1MTd9.I_g2woPxEz6ru-FNXMkuVPc42o53NQBYi7NyS9d_riE


### local auth/register : 
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "baliwme2014@gmail.com",
  "password": "Pass@word1",
  "role": "USER"
}

### Call images/4 with Auth:jwt
GET http://localhost:8080/images/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY2Fpc2JhY2tAb3V0bG9vay5jb20iLCJpYXQiOjE2NTM4OTYzMTAsImV4cCI6MTY1Mzg5NzIxMH0.IjJ7uOxCyFvlPQebFQOsR9EGELzVPWPn3PIy-8eW8hg


### Call images/2 with Auth:jwt
PATCH http://localhost:8080/images/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY2Fpc2JhY2tAb3V0bG9vay5jb20iLCJpYXQiOjE2NTM4OTYzMTAsImV4cCI6MTY1Mzg5NzIxMH0.IjJ7uOxCyFvlPQebFQOsR9EGELzVPWPn3PIy-8eW8hg

{
  "hits": 13,
  "uri": "https://bitcoin.org/img/icons/logotop.svg"
}

### Call images/4 with Auth:jwt
GET http://localhost:8080/images/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY2Fpc2JhY2tAb3V0bG9vay5jb20iLCJpYXQiOjE2NTM4OTYzMTAsImV4cCI6MTY1Mzg5NzIxMH0.IjJ7uOxCyFvlPQebFQOsR9EGELzVPWPn3PIy-8eW8hg


### Call images/2 with Auth:jwt
GET http://localhost:8080/images/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY2Fpc2JhY2tAb3V0bG9vay5jb20iLCJpYXQiOjE2NTM4OTYzMTAsImV4cCI6MTY1Mzg5NzIxMH0.IjJ7uOxCyFvlPQebFQOsR9EGELzVPWPn3PIy-8eW8hg


### Call images/ with Auth:jwt
GET http://localhost:8080/images/?limit=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiY2Fpc2JhY2tAb3V0bG9vay5jb20iLCJpYXQiOjE2NTM4OTYwNzIsImV4cCI6MTY1Mzg5Njk3Mn0.BcLyfduR9f0Lzo4A0shRIU8NG8NDWHuhQIG6tyN7w6U

### Local auth/login :  with new password
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "caisback@outlook.com",
  "password": "Pass@word1"
}

### local auth/register : 
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "caisback@outlook.com",
  "password": "Pass@word1",
  "role": "ADMIN"
}

###
GET http://localhost:8080/images/?limit=3
Content-Type: application/json



### 28.May.2022 12:56
### https://stackoverflow.com/questions/38406920/best-way-to-wait-for-foreach-to-complete



### 27.May.2022 05:29
### http://json2ts.com/
### https://github.com/cloudinary/cloudinary_npm/blob/master/samples/basic/basic.js
###  https://javascript.plainenglish.io/async-await-foreach-81d4859f2b8c
### 

GET http://localhost:8080/images/?limit=3
Content-Type: application/json



### Pexel API Call with page & per_page & size, to fixed maximum size
GET https://api.pexels.com/v1/search?query=people&orientation=square
Authorization: Bearer 563492ad6f9170000100000143b1404b9f7e475d8c8831687a2e36a9


#   message: 'Error in loading https://www.pexels.com/photo/man-wearing-jacket-standing-on-wooden-docks-leading-to-body-of-water-571169/ - 403 Forbidden',
#   name: 'Error',
#   http_code: 400
# }
#   message: 'Error in loading https://www.pexels.com/photo/little-boy-carrying-can-1125850/ - 403 Forbidden',
#   message: 'Error in loading https://www.pexels.com/photo/people-walking-in-market-439818/ - 403 Forbidden',


# {
#   asset_id: '58d3bed5f091f52303277505c27f9af0',
#   public_id: 'h0yibffo6jqxz1ytpu8v',
#   version: 1653724635,
#   version_id: 'd76b268037fc2bd28637d3f72626d609',
#   signature: 'dadfceb0cba04906717e0dea6294a436ba158eeb',
#   width: 400,
#   height: 300,
#   format: 'jpg',
#   resource_type: 'image',
#   created_at: '2022-05-28T07:57:15Z',
#   tags: [ 'basic_sample' ],
#   bytes: 206960,
#   type: 'upload',
#   etag: '9359a0f3ec878d32e06a456c4224b52b',
#   placeholder: false,
#   url: 'http://res.cloudinary.com/dhcnbaqsl/image/upload/v1653724635/h0yibffo6jqxz1ytpu8v.jpg',
#   secure_url: 'https://res.cloudinary.com/dhcnbaqsl/image/upload/v1653724635/h0yibffo6jqxz1ytpu8v.jpg',
#   original_filename: 'couple',
#   api_key: '342277832733615'
# }



### END-OF-DAY ###
### 27.May.2022 06:12
### https://support.cloudinary.com/hc/en-us/community/posts/360010327340-Invalid-Signature-String-to-sign


### 
GET http://localhost:8080/images/?limit=3
Content-Type: application/json


###
curl https://api.cloudinary.com/v1_1/demo/image/upload -X POST --data 'file=https://www.example.com/sample.jpg&timestamp=1653612483&api_key=342277832733615&signature=39240834322e64c7882351298c963a45a84d56c6'

### Live auth/login :  with new password
POST https://post-nestjs24hour.herokuapp.com/auth/login
Content-Type: application/json

{
  "email": "caisback@outlook.com",
  "password": "NewPass@word123"
}


### Live auth/password-reset : 
POST https://post-nestjs24hour.herokuapp.com/auth/password-new
Content-Type: application/json

{
  "password_reset_token": "$2b$10$26Iim0EAwT6gNlBN/91Uw.6NGyN.wtSg.DelM8WgZqxKWrWl1pUbC",
  "new_password": "NewPass@word123"
}


### Live auth/password-reset : 
POST https://post-nestjs24hour.herokuapp.com/auth/password-reset
Content-Type: application/json

{
  "email": "caisback@outlook.com"
}


### Live auth/login : 
POST https://post-nestjs24hour.herokuapp.com/auth/login
Content-Type: application/json

{
  "email": "caisback@outlook.com",
  "password": "Pass@word1"
}


### Live auth/register : 
POST https://post-nestjs24hour.herokuapp.com/auth/register
Content-Type: application/json

{
  "email": "caisback@outlook.com",
  "password": "Pass@word1",
  "role": "ADMIN"
}


### https://www.youtube.com/watch?v=lV6vty0Hf_E&list=PLsjmv9aDmNDBwFUXZbdfc4Xauvd-gDsLV&index=7
### https://progressivecoder.com/how-to-send-emails-using-nestjs-sendgrid-api/
### https://docs.nestjs.com/techniques/events#dispatching-events



### auth/password-reset call;
POST http://localhost:8080/auth/password-new
Content-Type: application/json

{
  "password_reset_token": "$2b$10$8EAeebZxIaLZEUdLyQX2/eLU9/ffxy.TE91OtlB93IefjOP5PTO12",
  "new_password": "Password@1234"

}




### auth/password-reset call;
POST http://localhost:8080/auth/password-reset
Content-Type: application/json

{
  "email": "baliwme2014@gmail.com"
}



### Login Valid user auth/login call;
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "baliwme2014@gmail.com",
  "password": "Pass@word1"
}


### Valid auth/register call;
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "baliwme2014@gmail.com",
  "password": "Pass@word1",
  "role": "ADMIN"
}

### Invalid auth/register call;
POST http://localhost:8080/auth/register
Content-Type: application/json


### 
GET http://localhost:8080/images/?limit=h
Content-Type: application/json


### END-OF_DAY##
### 25.May.2022 10:22
### Pipe: https://www.youtube.com/watch?v=DAjF0jkn6Nc AND i6Rt-DpbG_A
### https://www.youtube.com/watch?v=uAKzFhE3rxU
### https://mediajams.dev/post/Signed-Image-Uploading-to-Cloudinary-with-Angular-and-NestJS


###
curl https://api.cloudinary.com/v1_1/demo/image/upload -X POST --data 
'file=https://upload.wikimedia.org/wikipedia/commons/a/ae/Olympic_flag.jpg&public_id=olympic_flag&timestamp=12345678&api_key=98765432&signature=a123456f987664af'

### 11:18 Get nth number of Pexels images at random page:
GET http://localhost:3000/images/?limit=4
Content-Type: application/json


### Pexel API Call with page & per_page: 11:14
GET https://api.pexels.com/v1/search?query=people&page=2&per_page=3&size=small
Authorization: Bearer 563492ad6f9170000100000143b1404b9f7e475d8c8831687a2e36a9


### 10:22 Get nth number of Pexels images:
GET http://localhost:3000/images/?limit=5
Content-Type: application/json




### END-OF-DAY ###
### 11:17 Get nth number of Pexels images:
GET http://localhost:3000/images/?limit=7
Content-Type: application/json


### Pexel API Call: 08:11
GET https://api.pexels.com/v1/search?query=people
Authorization: Bearer 563492ad6f9170000100000143b1404b9f7e475d8c8831687a2e36a9


### With value with in the allowed range
GET http://localhost:3000/images/?limit=7
Content-Type: application/json

### With more than 10, 'limit=33', shuould return 10
GET http://localhost:3000/images/?limit=33
Content-Type: application/json

### With invalid 'limit=invalid'
GET http://localhost:3000/images/?limit=invalid
Content-Type: application/json

### 24.May.2022 07:47
### With no limit defined, should return 5 as default
GET http://localhost:3000/images
Content-Type: application/json